name: Build and deploy Docker image to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login to Azure Container Registry
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ambigdisambig-d9gmfyb8hccrd4f2.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-selenium-streamlit:latest .

      # Tag image with ACR repo
      - name: Tag Docker image
        run: docker tag my-selenium-streamlit:latest ambigdisambig-d9gmfyb8hccrd4f2.azurecr.io/my-selenium-streamlit:latest

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: docker push ambigdisambig-d9gmfyb8hccrd4f2.azurecr.io/my-selenium-streamlit:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'query-ambig-disambig'
          images: ambigdisambig-d9gmfyb8hccrd4f2.azurecr.io/my-selenium-streamlit:latest
